title: Basant Kumar Sharma # your name (or website title) here
logo: "/images/402250_Basant-Sharma.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Basant is a full stack developer, software engineer with broad and deep experience developing secure & scalable FinTech products. He has been working with product-based tech companies in India for over 11 years, helping to build technology-based businesses from the ground up. He excels at programming back-end (PHP, Python, NodeJS), front-end services (JavaScript, Angular) Hybrid application (Ionic) in a variety of languages, and holds a Master’s degree in Computer Application.
  <br><br>
  <a href="https://www.linkedin.com/in/basant-kumar-sharma/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
